# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a55WOCksSbaBdpdyiJ84ZVNavhoycjU5
"""

# Загрузка данных
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

# Загружаем датасет
iris = load_iris()
X = iris.data
y = iris.target

# Разбиваем на обучение и тест
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Обучаем модель
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Предсказываем
y_pred = model.predict(X_test)

# Смотрим точность
acc = accuracy_score(y_test, y_pred)
print(f"Точность модели: {acc:.2%}")

# Сохраним код в файл (для GitHub)
code = '''
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=42)

model = RandomForestClassifier()
model.fit(X_train, y_train)
acc = accuracy_score(y_test, model.predict(X_test))
print(f"Точность: {acc:.2%}")
'''

with open('iris_ml.py', 'w') as f:
    f.write(code)